spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music
    username: music
    password: l0c4lP4ss
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true